//! Reference:
//! - [6502 Instruction Tables](https://www.masswerk.at/6502/instruction-tables/)
//! - [NES on FPGA CPU](https://pgate1.at-ninja.jp/NES_on_FPGA/nes_cpu.htm#instruction)

macro_rules! define_ops {
    ($(($ops:ident) => ($($op:ident),*)),*) => {
        #[derive(Clone, Copy, Debug)]
        pub enum Operator{
            $($ops($ops)),*
        }

        $(
            #[derive(Clone, Copy, Debug)]
            #[allow(clippy::upper_case_acronyms)]
            pub enum $ops{
                $($op),*
            }

            $(
                const $op: Operator = Operator::$ops($ops::$op);
            )*
        )*
    };
}

define_ops! {
    (Implicit) => (JAM, INX, INY, DEX, DEY, CLC, CLD, CLI, CLV, SEC, SED, SEI, TAX, TAY, TSX, TXA, TYA, TXS),
    (Branch) => (BCC, BCS, BNE, BEQ, BVC, BVS, BPL, BMI),
    (ReadOp) => (NOP, ADC, SBC, AND, ORA, EOR, LDA, BIT, LDX, LDY, LAX, LXA, LAS, CMP, CPX, CPY, ALR, ARR, ANC, AXS, ANE),
    (ModifyOp) => (ASL, LSR, ROL, ROR, INC, DEC, DCP, ISB, RRA, RLA, SLO, SRE),
    (WriteOp) => (STA, STY, SAX, STX, SHA, SHX, SHY, SHS),
    (UniqueCycle) => (BRK, RTI, RTS, JSR, JMP, PHA, PHP, PLA, PLP)
}

#[derive(PartialEq, Eq, Clone, Copy, Debug)]
pub enum Addressing {
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Relative,
    XIdxedInd,
    IndYIdxed,
    AbsoluteInd,
}

pub const OPCODE_TABLE: [(Operator, Addressing); 256] = [
    /* 0x00 */ (BRK, Addressing::Implied),
    /* 0x01 */ (ORA, Addressing::XIdxedInd),
    /* 0x02 */ (JAM, Addressing::Implied),
    /* 0x03 */ (SLO, Addressing::XIdxedInd),
    /* 0x04 */ (NOP, Addressing::ZeroPage),
    /* 0x05 */ (ORA, Addressing::ZeroPage),
    /* 0x06 */ (ASL, Addressing::ZeroPage),
    /* 0x07 */ (SLO, Addressing::ZeroPage),
    /* 0x08 */ (PHP, Addressing::Implied),
    /* 0x09 */ (ORA, Addressing::Immediate),
    /* 0x0A */ (ASL, Addressing::Accumulator),
    /* 0x0B */ (ANC, Addressing::Immediate),
    /* 0x0C */ (NOP, Addressing::Absolute),
    /* 0x0D */ (ORA, Addressing::Absolute),
    /* 0x0E */ (ASL, Addressing::Absolute),
    /* 0x0F */ (SLO, Addressing::Absolute),
    /* 0x10 */ (BPL, Addressing::Relative),
    /* 0x11 */ (ORA, Addressing::IndYIdxed),
    /* 0x12 */ (JAM, Addressing::Implied),
    /* 0x13 */ (SLO, Addressing::IndYIdxed),
    /* 0x14 */ (NOP, Addressing::ZeroPageX),
    /* 0x15 */ (ORA, Addressing::ZeroPageX),
    /* 0x16 */ (ASL, Addressing::ZeroPageX),
    /* 0x17 */ (SLO, Addressing::ZeroPageX),
    /* 0x18 */ (CLC, Addressing::Implied),
    /* 0x19 */ (ORA, Addressing::AbsoluteY),
    /* 0x1A */ (NOP, Addressing::Implied),
    /* 0x1B */ (SLO, Addressing::AbsoluteY),
    /* 0x1C */ (NOP, Addressing::AbsoluteX),
    /* 0x1D */ (ORA, Addressing::AbsoluteX),
    /* 0x1E */ (ASL, Addressing::AbsoluteX),
    /* 0x1F */ (SLO, Addressing::AbsoluteX),
    /* 0x20 */ (JSR, Addressing::Absolute),
    /* 0x21 */ (AND, Addressing::XIdxedInd),
    /* 0x22 */ (JAM, Addressing::Implied),
    /* 0x23 */ (RLA, Addressing::XIdxedInd),
    /* 0x24 */ (BIT, Addressing::ZeroPage),
    /* 0x25 */ (AND, Addressing::ZeroPage),
    /* 0x26 */ (ROL, Addressing::ZeroPage),
    /* 0x27 */ (RLA, Addressing::ZeroPage),
    /* 0x28 */ (PLP, Addressing::Implied),
    /* 0x29 */ (AND, Addressing::Immediate),
    /* 0x2A */ (ROL, Addressing::Accumulator),
    /* 0x2B */ (ANC, Addressing::Immediate),
    /* 0x2C */ (BIT, Addressing::Absolute),
    /* 0x2D */ (AND, Addressing::Absolute),
    /* 0x2E */ (ROL, Addressing::Absolute),
    /* 0x2F */ (RLA, Addressing::Absolute),
    /* 0x30 */ (BMI, Addressing::Relative),
    /* 0x31 */ (AND, Addressing::IndYIdxed),
    /* 0x32 */ (JAM, Addressing::Implied),
    /* 0x33 */ (RLA, Addressing::IndYIdxed),
    /* 0x34 */ (NOP, Addressing::ZeroPageX),
    /* 0x35 */ (AND, Addressing::ZeroPageX),
    /* 0x36 */ (ROL, Addressing::ZeroPageX),
    /* 0x37 */ (RLA, Addressing::ZeroPageX),
    /* 0x38 */ (SEC, Addressing::Implied),
    /* 0x39 */ (AND, Addressing::AbsoluteY),
    /* 0x3A */ (NOP, Addressing::Implied),
    /* 0x3B */ (RLA, Addressing::AbsoluteY),
    /* 0x3C */ (NOP, Addressing::AbsoluteX),
    /* 0x3D */ (AND, Addressing::AbsoluteX),
    /* 0x3E */ (ROL, Addressing::AbsoluteX),
    /* 0x3F */ (RLA, Addressing::AbsoluteX),
    /* 0x40 */ (RTI, Addressing::Implied),
    /* 0x41 */ (EOR, Addressing::XIdxedInd),
    /* 0x42 */ (JAM, Addressing::Implied),
    /* 0x43 */ (SRE, Addressing::XIdxedInd),
    /* 0x44 */ (NOP, Addressing::ZeroPage),
    /* 0x45 */ (EOR, Addressing::ZeroPage),
    /* 0x46 */ (LSR, Addressing::ZeroPage),
    /* 0x47 */ (SRE, Addressing::ZeroPage),
    /* 0x48 */ (PHA, Addressing::Implied),
    /* 0x49 */ (EOR, Addressing::Immediate),
    /* 0x4A */ (LSR, Addressing::Accumulator),
    /* 0x4B */ (ALR, Addressing::Immediate),
    /* 0x4C */ (JMP, Addressing::Absolute),
    /* 0x4D */ (EOR, Addressing::Absolute),
    /* 0x4E */ (LSR, Addressing::Absolute),
    /* 0x4F */ (SRE, Addressing::Absolute),
    /* 0x50 */ (BVC, Addressing::Relative),
    /* 0x51 */ (EOR, Addressing::IndYIdxed),
    /* 0x52 */ (JAM, Addressing::Implied),
    /* 0x53 */ (SRE, Addressing::IndYIdxed),
    /* 0x54 */ (NOP, Addressing::ZeroPageX),
    /* 0x55 */ (EOR, Addressing::ZeroPageX),
    /* 0x56 */ (LSR, Addressing::ZeroPageX),
    /* 0x57 */ (SRE, Addressing::ZeroPageX),
    /* 0x58 */ (CLI, Addressing::Implied),
    /* 0x59 */ (EOR, Addressing::AbsoluteY),
    /* 0x5A */ (NOP, Addressing::Implied),
    /* 0x5B */ (SRE, Addressing::AbsoluteY),
    /* 0x5C */ (NOP, Addressing::AbsoluteX),
    /* 0x5D */ (EOR, Addressing::AbsoluteX),
    /* 0x5E */ (LSR, Addressing::AbsoluteX),
    /* 0x5F */ (SRE, Addressing::AbsoluteX),
    /* 0x60 */ (RTS, Addressing::Implied),
    /* 0x61 */ (ADC, Addressing::XIdxedInd),
    /* 0x62 */ (JAM, Addressing::Implied),
    /* 0x63 */ (RRA, Addressing::XIdxedInd),
    /* 0x64 */ (NOP, Addressing::ZeroPage),
    /* 0x65 */ (ADC, Addressing::ZeroPage),
    /* 0x66 */ (ROR, Addressing::ZeroPage),
    /* 0x67 */ (RRA, Addressing::ZeroPage),
    /* 0x68 */ (PLA, Addressing::Implied),
    /* 0x69 */ (ADC, Addressing::Immediate),
    /* 0x6A */ (ROR, Addressing::Accumulator),
    /* 0x6B */ (ARR, Addressing::Immediate),
    /* 0x6C */ (JMP, Addressing::AbsoluteInd),
    /* 0x6D */ (ADC, Addressing::Absolute),
    /* 0x6E */ (ROR, Addressing::Absolute),
    /* 0x6F */ (RRA, Addressing::Absolute),
    /* 0x70 */ (BVS, Addressing::Relative),
    /* 0x71 */ (ADC, Addressing::IndYIdxed),
    /* 0x72 */ (JAM, Addressing::Implied),
    /* 0x73 */ (RRA, Addressing::IndYIdxed),
    /* 0x74 */ (NOP, Addressing::ZeroPageX),
    /* 0x75 */ (ADC, Addressing::ZeroPageX),
    /* 0x76 */ (ROR, Addressing::ZeroPageX),
    /* 0x77 */ (RRA, Addressing::ZeroPageX),
    /* 0x78 */ (SEI, Addressing::Implied),
    /* 0x79 */ (ADC, Addressing::AbsoluteY),
    /* 0x7A */ (NOP, Addressing::Implied),
    /* 0x7B */ (RRA, Addressing::AbsoluteY),
    /* 0x7C */ (NOP, Addressing::AbsoluteX),
    /* 0x7D */ (ADC, Addressing::AbsoluteX),
    /* 0x7E */ (ROR, Addressing::AbsoluteX),
    /* 0x7F */ (RRA, Addressing::AbsoluteX),
    /* 0x80 */ (NOP, Addressing::Immediate),
    /* 0x81 */ (STA, Addressing::XIdxedInd),
    /* 0x82 */ (NOP, Addressing::Immediate),
    /* 0x83 */ (SAX, Addressing::XIdxedInd),
    /* 0x84 */ (STY, Addressing::ZeroPage),
    /* 0x85 */ (STA, Addressing::ZeroPage),
    /* 0x86 */ (STX, Addressing::ZeroPage),
    /* 0x87 */ (SAX, Addressing::ZeroPage),
    /* 0x88 */ (DEY, Addressing::Implied),
    /* 0x89 */ (NOP, Addressing::Immediate),
    /* 0x8A */ (TXA, Addressing::Implied),
    /* 0x8B */ (ANE, Addressing::Immediate),
    /* 0x8C */ (STY, Addressing::Absolute),
    /* 0x8D */ (STA, Addressing::Absolute),
    /* 0x8E */ (STX, Addressing::Absolute),
    /* 0x8F */ (SAX, Addressing::Absolute),
    /* 0x90 */ (BCC, Addressing::Relative),
    /* 0x91 */ (STA, Addressing::IndYIdxed),
    /* 0x92 */ (JAM, Addressing::Implied),
    /* 0x93 */ (SHA, Addressing::IndYIdxed),
    /* 0x94 */ (STY, Addressing::ZeroPageX),
    /* 0x95 */ (STA, Addressing::ZeroPageX),
    /* 0x96 */ (STX, Addressing::ZeroPageY),
    /* 0x97 */ (SAX, Addressing::ZeroPageY),
    /* 0x98 */ (TYA, Addressing::Implied),
    /* 0x99 */ (STA, Addressing::AbsoluteY),
    /* 0x9A */ (TXS, Addressing::Implied),
    /* 0x9B */ (SHS, Addressing::AbsoluteY),
    /* 0x9C */ (SHY, Addressing::AbsoluteX),
    /* 0x9D */ (STA, Addressing::AbsoluteX),
    /* 0x9E */ (SHX, Addressing::AbsoluteY),
    /* 0x9F */ (SHA, Addressing::AbsoluteY),
    /* 0xA0 */ (LDY, Addressing::Immediate),
    /* 0xA1 */ (LDA, Addressing::XIdxedInd),
    /* 0xA2 */ (LDX, Addressing::Immediate),
    /* 0xA3 */ (LAX, Addressing::XIdxedInd),
    /* 0xA4 */ (LDY, Addressing::ZeroPage),
    /* 0xA5 */ (LDA, Addressing::ZeroPage),
    /* 0xA6 */ (LDX, Addressing::ZeroPage),
    /* 0xA7 */ (LAX, Addressing::ZeroPage),
    /* 0xA8 */ (TAY, Addressing::Implied),
    /* 0xA9 */ (LDA, Addressing::Immediate),
    /* 0xAA */ (TAX, Addressing::Implied),
    /* 0xAB */ (LXA, Addressing::Immediate),
    /* 0xAC */ (LDY, Addressing::Absolute),
    /* 0xAD */ (LDA, Addressing::Absolute),
    /* 0xAE */ (LDX, Addressing::Absolute),
    /* 0xAF */ (LAX, Addressing::Absolute),
    /* 0xB0 */ (BCS, Addressing::Relative),
    /* 0xB1 */ (LDA, Addressing::IndYIdxed),
    /* 0xB2 */ (JAM, Addressing::Implied),
    /* 0xB3 */ (LAX, Addressing::IndYIdxed),
    /* 0xB4 */ (LDY, Addressing::ZeroPageX),
    /* 0xB5 */ (LDA, Addressing::ZeroPageX),
    /* 0xB6 */ (LDX, Addressing::ZeroPageY),
    /* 0xB7 */ (LAX, Addressing::ZeroPageY),
    /* 0xB8 */ (CLV, Addressing::Implied),
    /* 0xB9 */ (LDA, Addressing::AbsoluteY),
    /* 0xBA */ (TSX, Addressing::Implied),
    /* 0xBB */ (LAS, Addressing::AbsoluteY),
    /* 0xBC */ (LDY, Addressing::AbsoluteX),
    /* 0xBD */ (LDA, Addressing::AbsoluteX),
    /* 0xBE */ (LDX, Addressing::AbsoluteY),
    /* 0xBF */ (LAX, Addressing::AbsoluteY),
    /* 0xC0 */ (CPY, Addressing::Immediate),
    /* 0xC1 */ (CMP, Addressing::XIdxedInd),
    /* 0xC2 */ (NOP, Addressing::Immediate),
    /* 0xC3 */ (DCP, Addressing::XIdxedInd),
    /* 0xC4 */ (CPY, Addressing::ZeroPage),
    /* 0xC5 */ (CMP, Addressing::ZeroPage),
    /* 0xC6 */ (DEC, Addressing::ZeroPage),
    /* 0xC7 */ (DCP, Addressing::ZeroPage),
    /* 0xC8 */ (INY, Addressing::Implied),
    /* 0xC9 */ (CMP, Addressing::Immediate),
    /* 0xCA */ (DEX, Addressing::Implied),
    /* 0xCB */ (AXS, Addressing::Immediate),
    /* 0xCC */ (CPY, Addressing::Absolute),
    /* 0xCD */ (CMP, Addressing::Absolute),
    /* 0xCE */ (DEC, Addressing::Absolute),
    /* 0xCF */ (DCP, Addressing::Absolute),
    /* 0xD0 */ (BNE, Addressing::Relative),
    /* 0xD1 */ (CMP, Addressing::IndYIdxed),
    /* 0xD2 */ (JAM, Addressing::Implied),
    /* 0xD3 */ (DCP, Addressing::IndYIdxed),
    /* 0xD4 */ (NOP, Addressing::ZeroPageX),
    /* 0xD5 */ (CMP, Addressing::ZeroPageX),
    /* 0xD6 */ (DEC, Addressing::ZeroPageX),
    /* 0xD7 */ (DCP, Addressing::ZeroPageX),
    /* 0xD8 */ (CLD, Addressing::Implied),
    /* 0xD9 */ (CMP, Addressing::AbsoluteY),
    /* 0xDA */ (NOP, Addressing::Implied),
    /* 0xDB */ (DCP, Addressing::AbsoluteY),
    /* 0xDC */ (NOP, Addressing::AbsoluteX),
    /* 0xDD */ (CMP, Addressing::AbsoluteX),
    /* 0xDE */ (DEC, Addressing::AbsoluteX),
    /* 0xDF */ (DCP, Addressing::AbsoluteX),
    /* 0xE0 */ (CPX, Addressing::Immediate),
    /* 0xE1 */ (SBC, Addressing::XIdxedInd),
    /* 0xE2 */ (NOP, Addressing::Immediate),
    /* 0xE3 */ (ISB, Addressing::XIdxedInd),
    /* 0xE4 */ (CPX, Addressing::ZeroPage),
    /* 0xE5 */ (SBC, Addressing::ZeroPage),
    /* 0xE6 */ (INC, Addressing::ZeroPage),
    /* 0xE7 */ (ISB, Addressing::ZeroPage),
    /* 0xE8 */ (INX, Addressing::Implied),
    /* 0xE9 */ (SBC, Addressing::Immediate),
    /* 0xEA */ (NOP, Addressing::Implied),
    /* 0xEB */ (SBC, Addressing::Immediate),
    /* 0xEC */ (CPX, Addressing::Absolute),
    /* 0xED */ (SBC, Addressing::Absolute),
    /* 0xEE */ (INC, Addressing::Absolute),
    /* 0xEF */ (ISB, Addressing::Absolute),
    /* 0xF0 */ (BEQ, Addressing::Relative),
    /* 0xF1 */ (SBC, Addressing::IndYIdxed),
    /* 0xF2 */ (JAM, Addressing::Implied),
    /* 0xF3 */ (ISB, Addressing::IndYIdxed),
    /* 0xF4 */ (NOP, Addressing::ZeroPageX),
    /* 0xF5 */ (SBC, Addressing::ZeroPageX),
    /* 0xF6 */ (INC, Addressing::ZeroPageX),
    /* 0xF7 */ (ISB, Addressing::ZeroPageX),
    /* 0xF8 */ (SED, Addressing::Implied),
    /* 0xF9 */ (SBC, Addressing::AbsoluteY),
    /* 0xFA */ (NOP, Addressing::Implied),
    /* 0xFB */ (ISB, Addressing::AbsoluteY),
    /* 0xFC */ (NOP, Addressing::AbsoluteX),
    /* 0xFD */ (SBC, Addressing::AbsoluteX),
    /* 0xFE */ (INC, Addressing::AbsoluteX),
    /* 0xFF */ (ISB, Addressing::AbsoluteX),
];
